[theme]
primaryColor = "#aa0000ff"
backgroundColor = "black"
secondaryBackgroundColor = "black"
textColor= "#aa0000ff"
borderColor = "#aa0000ff"

[theme.sidebar]
primaryColor="black" 
secondaryBackgroundColor ="#aa0000ff" 
backgroundColor = "#aa0000ff" 
textColor="white"
showWidgetBorder = true
borderColor = "white"
